export const LAB_STORY_TEXT = {
  en: {
    brand: "Detective Academy",
    subtitle: "Projective Simulation",
    modes: "Modes",
    returnModes: "Return to mode selection",
    kicker: "Nova’s advanced training",
    title: "Learning Research lab",
    summary: "Design Nova’s training room and rewards. Compare how glow, forgetting and policy greediness change her learning at the Detective Academy.",
    trainingRoom: "Training room",
    environmentHint: "Nova explores the room you design.",
    memoryTitle: "Nova’s memory",
    memoryHint: "One cell for each position in the training room.",
    progressTitle: "Learning progress",
    progressHint: "Follow the rewards from Nova’s investigations.",
    roomEditor: "Environment settings",
    tuneMemory: "Tune Nova’s learning",
    temperatureLabel: "Policy greediness (inverse temperature β)",
    temperatureHelp: "β = 0 gives all four actions the same probability. Increasing β favors larger H-values more strongly; smaller β allows more exploration. There is no separate exploration parameter.",
    successCriterion: "Success: shortest-path probability ≥ 75%",
    successExplanation: "At the end of each episode, sum the current policy’s probabilities of all minimum-step routes to the watch, including required keys and doors.",
    minimumSteps: "minimum steps",
    awaitEpisode: "Evaluated at the end of an episode.",
    noRoute: "No valid route to the watch. Edit the training room.",
    glowExplanation: "The chosen percept–action pair has glow 1. Every other pair fades by the factor (1 − η) after each step. Glow always stays between 0 and 1.",
    playback: "Display mode",
    playbackModes: { click: "Click", slow: "Slow", fast: "Fast", immediate: "Immediate" },
    playbackHints: { click: "Click Step to sample one action and move Nova.", slow: "Watch each decision slowly, with a pause after every episode.", fast: "Watch the same learning process with faster steps and episode pauses.", immediate: "Show only episode endings, with their glow and last decision." },
    step: "Step",
    nextStep: "Next episode: step",
    currentPercept: "Current percept",
    currentAction: "Current action",
    decisionHint: "The position used to sample this action. Colors and objects are visual labels.",
    noAction: "Not sampled yet",
    episodeFinished: "Episode finished",
    episodeOutcomes: { goal: "Watch recovered", trap: "Trap reached", limit: "Step limit reached" },
    hExplanation: "H-values are learned connection strengths. Reward, forgetting, and reward sensitivity change them over time.",
    policyExplanation: "The policy shows the actual action probabilities: softmax of the H-values multiplied by inverse temperature β. Larger β favors strong connections; β = 0 explores uniformly.",
    coachObservation: "Coach’s observation",
    observation: "Nova learns from the feedback you define—not from your intentions. Compare her memory with the reward curves before changing another setting.",
    novaPortrait: "Nova portrait",
    agentLabel: "Detective student Nova",
    share: "Share the academy",
    case: "Case",
    trajectories: "trajectories",
    memoryShown: "Nova’s memory shown as {view}",
    memoryRepresentation: "Memory representation",
    glow: "Glow",
    hValues: "H-values",
    policy: "Policy",
    actions: ["up", "right", "down", "left"],
    novaPosition: "Nova’s current position",
    cases: [
      { name: "The first missing watch", description: "Help Nova learn in a small training room.", instructions: "A watch is missing in the training room. Nova starts at the bottom-left and must learn to reach it at the top-right through trial and error. Run the training, compare glow, H-values, and policy, and observe the rewards. Objects are decorative: Nova’s percept is her grid position." },
      { name: "A detective’s memory", description: "Experiment with how Nova remembers useful decisions.", instructions: "Keep the same case and investigate Nova’s memory. Change forgetting, reward sensitivity, and glow decay to see which settings help her recover the watch reliably. The task and rewards stay fixed so you can focus on learning." },
      { name: "The narrow passage", description: "Recover the watch through a constrained training room.", instructions: "Nova’s route now passes through a narrow corridor. Design the room and adjust the available rewards and learning parameters. Compare the decisions in memory with the trajectories she actually takes." },
      { name: "Behind a locked door", description: "Find the matching key before recovering the watch.", instructions: "The watch lies beyond a locked door. Nova must collect the matching colored key to pass through it. Experiment with the learning settings to help Nova discover the key–door sequence." },
      { name: "The academy’s final case", description: "Find the watch while avoiding hazards and dead ends.", instructions: "Build a challenging training room with walls, hazards, keys, and doors. Define the rewards and tune Nova’s learning. Can she recover the watch consistently? Compare the memory views and learning curves rather than judging one lucky trajectory." },
    ],
  },
  de: {
    brand: "Detektivakademie",
    subtitle: "Projektive Simulation",
    modes: "Modi",
    returnModes: "Zur Modusauswahl zurückkehren",
    kicker: "Novas Training für Fortgeschrittene",
    title: "Lernforschungslabor",
    summary: "Gestalte Novas Trainingsraum und Belohnungen an der Detektivakademie. Vergleiche, wie Glow, Vergessen und Policy-Zielstrebigkeit ihr Lernen verändern.",
    trainingRoom: "Trainingsraum",
    environmentHint: "Nova erkundet den Raum, den du gestaltest.",
    memoryTitle: "Novas Gedächtnis",
    memoryHint: "Eine Gedächtniszelle für jede Position im Trainingsraum.",
    progressTitle: "Lernfortschritt",
    progressHint: "Verfolge die Belohnungen aus Novas Ermittlungen.",
    roomEditor: "Umgebungseinstellungen",
    tuneMemory: "Novas Lernen abstimmen",
    temperatureLabel: "Policy-Zielstrebigkeit (inverse Temperatur β)",
    temperatureHelp: "Bei β = 0 sind alle vier Aktionen gleich wahrscheinlich. Ein größeres β bevorzugt größere H-Werte stärker; ein kleineres β erlaubt mehr Exploration. Es gibt keinen separaten Explorationsparameter.",
    successCriterion: "Erfolg: Kürzeste-Wege-Wahrscheinlichkeit ≥ 75%",
    successExplanation: "Am Ende jeder Episode werden die Wahrscheinlichkeiten aller Wege mit minimaler Schrittzahl zur Uhr unter der aktuellen Policy addiert – einschließlich benötigter Schlüssel und Türen.",
    minimumSteps: "minimale Schritte",
    awaitEpisode: "Auswertung am Ende einer Episode.",
    noRoute: "Kein gültiger Weg zur Uhr. Passe den Trainingsraum an.",
    glowExplanation: "Das gewählte Perzept–Aktions-Paar hat Glow 1. Alle anderen Paare verblassen nach jedem Schritt mit dem Faktor (1 − η). Glow bleibt immer zwischen 0 und 1.",
    playback: "Anzeigemodus",
    playbackModes: { click: "Klick", slow: "Langsam", fast: "Schnell", immediate: "Sofort" },
    playbackHints: { click: "Klicke auf Schritt, um eine Aktion zu ziehen und Nova zu bewegen.", slow: "Beobachte jede Entscheidung langsam, mit einer Pause nach jeder Episode.", fast: "Beobachte denselben Lernprozess mit schnelleren Schritten und Episodenpausen.", immediate: "Zeige nur die Episodenenden mit ihrem Glow und der letzten Entscheidung." },
    step: "Schritt",
    nextStep: "Nächste Episode: Schritt",
    currentPercept: "Aktuelles Perzept",
    currentAction: "Aktuelle Aktion",
    decisionHint: "Die Position, an der diese Aktion gezogen wurde. Farben und Gegenstände sind visuelle Bezeichnungen.",
    noAction: "Noch nicht gezogen",
    episodeFinished: "Episode beendet",
    episodeOutcomes: { goal: "Uhr gefunden", trap: "Falle erreicht", limit: "Schrittlimit erreicht" },
    hExplanation: "H-Werte sind erlernte Verbindungsstärken. Belohnung, Vergessen und Belohnungssensitivität verändern sie mit der Zeit.",
    policyExplanation: "Die Policy zeigt die tatsächlichen Aktionswahrscheinlichkeiten: Softmax der H-Werte multipliziert mit der inversen Temperatur β. Ein größeres β bevorzugt starke Verbindungen; β = 0 erkundet gleichverteilt.",
    coachObservation: "Beobachtung des Coaches",
    observation: "Nova lernt aus dem Feedback, das du festlegst, nicht aus deinen Absichten. Vergleiche ihr Gedächtnis mit den Belohnungskurven, bevor du eine weitere Einstellung änderst.",
    novaPortrait: "Porträt von Nova",
    agentLabel: "Detektivschülerin Nova",
    share: "Akademie teilen",
    case: "Fall",
    trajectories: "Trajektorien",
    memoryShown: "Novas Gedächtnis als {view}",
    memoryRepresentation: "Darstellung des Gedächtnisses",
    glow: "Glow",
    hValues: "H-Werte",
    policy: "Policy",
    actions: ["oben", "rechts", "unten", "links"],
    novaPosition: "Novas aktuelle Position",
    cases: [
      { name: "Die erste verlorene Uhr", description: "Hilf Nova, in einem kleinen Trainingsraum zu lernen.", instructions: "Im Trainingsraum ist eine Uhr verschwunden. Nova startet unten links und soll durch Versuch und Irrtum lernen, die Uhr oben rechts zu erreichen. Starte das Training, vergleiche Glow, H-Werte und Policy und beobachte die Belohnungen. Die Gegenstände sind Dekoration: Novas Perzept ist ihre Rasterposition." },
      { name: "Das Gedächtnis einer Detektivin", description: "Untersuche, wie Nova nützliche Entscheidungen behält.", instructions: "Bleibe beim selben Fall und untersuche Novas Gedächtnis. Verändere Vergessen, Belohnungssensitivität und Glow-Abbau, um Einstellungen für ein zuverlässiges Wiederfinden der Uhr zu entdecken. Aufgabe und Belohnungen bleiben gleich, damit du dich auf das Lernen konzentrieren kannst." },
      { name: "Der schmale Durchgang", description: "Finde die Uhr in einem eingeengten Trainingsraum.", instructions: "Novas Weg führt nun durch einen schmalen Korridor. Gestalte den Raum und passe die verfügbaren Belohnungen und Lernparameter an. Vergleiche die Entscheidungen im Gedächtnis mit den Trajektorien, die sie tatsächlich nimmt." },
      { name: "Hinter einer verschlossenen Tür", description: "Finde den passenden Schlüssel vor der verlorenen Uhr.", instructions: "Die Uhr liegt hinter einer verschlossenen Tür. Nova muss den farblich passenden Schlüssel sammeln, um hindurchzugehen. Experimentiere mit den Lerneinstellungen, um Nova die Schlüssel-Tür-Abfolge entdecken zu lassen." },
      { name: "Der Abschlussfall der Akademie", description: "Finde die Uhr trotz Gefahren und Sackgassen.", instructions: "Baue einen anspruchsvollen Trainingsraum mit Wänden, Gefahren, Schlüsseln und Türen. Lege die Belohnungen fest und stimme Novas Lernen ab. Kann sie die Uhr zuverlässig finden? Vergleiche die Gedächtnisansichten und Lernkurven, statt eine einzelne glückliche Trajektorie zu beurteilen." },
    ],
  },
};
