const LAB_STORY_TEXT_CORE = {
  en: {
    brand: "Detective Academy",
    subtitle: "Projective Simulation",
    modes: "Modes",
    returnModes: "Return to mode selection",
    kicker: "Nova’s advanced training",
    title: "Learning Research lab",
    summary: "Design Nova’s training room and rewards. Compare how glow, forgetting and policy greediness change her learning at the Detective Academy.",
    trainingRoom: "Training room",
    environmentHint: "Nova explores your room. Watch reward: +{reward}.",
    memoryTitle: "Nova’s memory",
    memoryHint: "Associations are shared by cells with the same percept.",
    progressTitle: "Learning progress",
    progressHint: "Follow the rewards from Nova’s investigations.",
    roomEditor: "Environment settings",
    tuneMemory: "Tune Nova’s learning",
    temperatureLabel: "Policy greediness (inverse temperature β)",
    temperatureHelp: "Explore samples actions broadly, balance combines exploration with learned preferences, and exploit strongly favors the largest H-values.",
    successCriterion: "Success: shortest-path probability ≥ 75%",
    successExplanation: "At the end of each episode, the probabilities of all shortest successful routes are added. Case 3 separately evaluates reaching the key, opening the door, and the shortest route from the door to the watch. Case 4 allows two extra steps. Case 2 ends with a quiz after comparing exploration settings.",
    minimumSteps: "minimum steps",
    awaitEpisode: "Evaluated at the end of an episode.",
    noRoute: "No valid route to the watch. Edit the training room.",
    glowExplanation: "The chosen percept–action pair has glow 1. Every other pair fades by the factor (1 − η) after each step. Glow always stays between 0 and 1.",
    playback: "Display mode",
    playbackModes: { click: "Click", slow: "Slow", fast: "Fast", immediate: "Immediate" },
    playbackHints: { click: "Click Step to sample one action and move Nova.", slow: "Watch each decision slowly, with a pause after every episode.", fast: "Watch the same learning process with faster steps and episode pauses.", immediate: "Show only episode endings, with their glow and last decision." },
    step: "Step",
    nextStep: "Next episode: step",
    currentPercept: "Current percept",
    currentAction: "Current action",
    decisionHint: "Nova chose this action from the color, object, and key status she perceived here.",
    noAction: "Not sampled yet",
    episodeFinished: "Episode finished",
    episodeOutcomes: { goal: "Watch recovered", trap: "Trap reached", limit: "Step limit reached" },
    hExplanation: "H-values are learned connection strengths. Reward, forgetting, and reward sensitivity change them over time.",
    policyExplanation: "The policy shows the actual action probabilities: softmax of the H-values multiplied by inverse temperature β. Larger β favors strong connections; β = 0 explores uniformly.",
    coachObservation: "Coach’s observation",
    observation: "Nova learns from the feedback you define—not from your intentions. Compare her memory with the reward curves before changing another setting.",
    novaPortrait: "Nova portrait",
    agentLabel: "Detective student Nova",
    share: "Share the academy",
    case: "Case",
    trajectories: "trajectories",
    memoryShown: "Nova’s memory shown as {view}",
    memoryRepresentation: "Memory representation",
    glow: "Glow",
    hValues: "H-values",
    policy: "Policy",
    explorePrompt: "Nova has seen every color. Move her under explore, balance, and exploit. Watch five real trajectories at each setting, then compare her policy and location histograms.",
    explore: "Explore",
    balanced: "Balanced",
    exploit: "Exploit",
    compareModes: "Compare exploration settings",
    compareRunHint: "Choose a setting, then use Step or Run above the room. Complete five trajectories for each setting.",
    mapView: "Map view",
    fiveTrajectories: "Run five trajectories",
    visited: "Visits since changing the exploration setting",
    quizQuestion: "What happens when β increases?",
    quizAnswers: ["Nova forgets faster", "Nova favors actions with stronger H-values", "The colors become unique"],
    quizTryAgain: "Try another answer or compare the policies again.",
    reviewModes: "Review the three modes",
    takeQuiz: "Take the quiz",
    continue: "Continue",
    youWon: "You won!",
    keyAbsent: "Without key",
    keyPresent: "With key",
    actions: ["up", "right", "down", "left"],
    novaPosition: "Nova’s current position",
    cases: [
      { name: "Tune the memory yourself!", description: "Apply what you learned in Adventure mode.", instructions: "Nova graduated from the maze and reached the next training room. Tune glow and forgetting, and train Nova to find the watch as fast as possible." },
      { name: "Nova sees the world differently!", description: "So confusing: some rooms are identical!", instructions: "Watch how Nova represents her associations between what she sees and how she thinks she should behave. Guess! It's not a map!" },
      { name: "You are the boss! ", description: "Tune all memory parameters in one go!", instructions: "Train three skills: reach the key, open the door, and then take a shortest route from the door to the watch, each with probability above 75%. The key and first door opening give +1 each; trying the locked door without a key costs −1, and the watch gives +10." },
      { name: "Create your own training room.", description: "Design the environment and train Nova.", instructions: "Get creative! Distribute percepts, set traps and reward learning milestones!" },
    ],
  },
  de: {
    brand: "Detektivakademie",
    subtitle: "Projektive Simulation",
    modes: "Modi",
    returnModes: "Zur Modusauswahl zurückkehren",
    kicker: "Novas Training für Fortgeschrittene",
    title: "Lernforschungslabor",
    summary: "Gestalte Novas Trainingsraum und Belohnungen an der Detektivakademie. Vergleiche, wie Glow, Vergessen und Policy-Zielstrebigkeit ihr Lernen verändern.",
    trainingRoom: "Trainingsraum",
    environmentHint: "Nova erkundet deinen Raum. Belohnung für die Uhr: +{reward}.",
    memoryTitle: "Novas Gedächtnis",
    memoryHint: "Zellen mit demselben Perzept teilen sich Verknüpfungen.",
    progressTitle: "Lernfortschritt",
    progressHint: "Verfolge die Belohnungen aus Novas Ermittlungen.",
    roomEditor: "Umgebungseinstellungen",
    tuneMemory: "Novas Lernen abstimmen",
    temperatureLabel: "Policy-Zielstrebigkeit (inverse Temperatur β)",
    temperatureHelp: "Erkunden verteilt die Aktionen breit, Ausgewogen verbindet Exploration mit Gelerntem und Nutzen bevorzugt die größten H-Werte stark.",
    successCriterion: "Erfolg: Kürzeste-Wege-Wahrscheinlichkeit ≥ 75%",
    successExplanation: "Am Ende jeder Episode werden die Wahrscheinlichkeiten aller kürzesten erfolgreichen Wege addiert. Fall 3 bewertet Schlüssel, Türöffnung und den kürzesten Weg von der Tür zur Uhr getrennt. Fall 4 erlaubt zwei Zusatzschritte. Fall 2 endet nach dem Explorationsvergleich mit einem Quiz.",
    minimumSteps: "minimale Schritte",
    awaitEpisode: "Auswertung am Ende einer Episode.",
    noRoute: "Kein gültiger Weg zur Uhr. Passe den Trainingsraum an.",
    glowExplanation: "Das gewählte Perzept–Aktions-Paar hat Glow 1. Alle anderen Paare verblassen nach jedem Schritt mit dem Faktor (1 − η). Glow bleibt immer zwischen 0 und 1.",
    playback: "Anzeigemodus",
    playbackModes: { click: "Klick", slow: "Langsam", fast: "Schnell", immediate: "Sofort" },
    playbackHints: { click: "Klicke auf Schritt, um eine Aktion zu ziehen und Nova zu bewegen.", slow: "Beobachte jede Entscheidung langsam, mit einer Pause nach jeder Episode.", fast: "Beobachte denselben Lernprozess mit schnelleren Schritten und Episodenpausen.", immediate: "Zeige nur die Episodenenden mit ihrem Glow und der letzten Entscheidung." },
    step: "Schritt",
    nextStep: "Nächste Episode: Schritt",
    currentPercept: "Aktuelles Perzept",
    currentAction: "Aktuelle Aktion",
    decisionHint: "Nova wählte diese Aktion anhand der Farbe, des Gegenstands und ihres Schlüsselstatus an dieser Stelle.",
    noAction: "Noch nicht gezogen",
    episodeFinished: "Episode beendet",
    episodeOutcomes: { goal: "Uhr gefunden", trap: "Falle erreicht", limit: "Schrittlimit erreicht" },
    hExplanation: "H-Werte sind erlernte Verbindungsstärken. Belohnung, Vergessen und Belohnungssensitivität verändern sie mit der Zeit.",
    policyExplanation: "Die Policy zeigt die tatsächlichen Aktionswahrscheinlichkeiten: Softmax der H-Werte multipliziert mit der inversen Temperatur β. Ein größeres β bevorzugt starke Verbindungen; β = 0 erkundet gleichverteilt.",
    coachObservation: "Beobachtung des Coaches",
    observation: "Nova lernt aus dem Feedback, das du festlegst, nicht aus deinen Absichten. Vergleiche ihr Gedächtnis mit den Belohnungskurven, bevor du eine weitere Einstellung änderst.",
    novaPortrait: "Porträt von Nova",
    agentLabel: "Detektivschülerin Nova",
    share: "Akademie teilen",
    case: "Fall",
    trajectories: "Trajektorien",
    memoryShown: "Novas Gedächtnis als {view}",
    memoryRepresentation: "Darstellung des Gedächtnisses",
    glow: "Glow",
    hValues: "H-Werte",
    policy: "Policy",
    explorePrompt: "Nova hat jede Farbe gesehen. Bewege sie mit Erkunden, Ausgewogen und Nutzen. Beobachte jeweils fünf echte Trajektorien und vergleiche ihre Policy und die Ortshistogramme.",
    explore: "Erkunden",
    balanced: "Ausgewogen",
    exploit: "Nutzen",
    compareModes: "Exploration vergleichen",
    compareRunHint: "Wähle eine Einstellung und nutze Schritt oder Start über dem Raum. Schließe für jede Einstellung fünf Trajektorien ab.",
    mapView: "Kartenansicht",
    fiveTrajectories: "Fünf Trajektorien starten",
    visited: "Besuche seit dem Wechsel der Explorationseinstellung",
    quizQuestion: "Was geschieht, wenn β größer wird?",
    quizAnswers: ["Nova vergisst schneller", "Nova bevorzugt Aktionen mit stärkeren H-Werten", "Die Farben werden einzigartig"],
    quizTryAgain: "Probiere eine andere Antwort oder vergleiche die Policies erneut.",
    reviewModes: "Die drei Einstellungen ansehen",
    takeQuiz: "Zum Quiz",
    continue: "Weiter",
    youWon: "Du hast gewonnen!",
    keyAbsent: "Ohne Schlüssel",
    keyPresent: "Mit Schlüssel",
    actions: ["oben", "rechts", "unten", "links"],
    novaPosition: "Novas aktuelle Position",
    cases: [
      { name: "Stimme das Gedächtnis selbst ab und hilf Nova, die Uhr möglichst schnell zu finden", description: "Wende dein Wissen aus dem Abenteuermodus an.", instructions: "Jede Zelle hat ein eigenes Farb- und Gegenstandsperzept. Stimme Glow und Vergessen ab, bis die gemeinsame Wahrscheinlichkeit aller kürzesten Wege zur Uhr 75 % erreicht." },
      { name: "Nova sieht die Welt anders!", description: "Wiederholte Farben teilen sich ein Gedächtnis.", instructions: "Nova sieht nur wenige Farben und außer der Uhr keine Gegenstände. Gleichfarbige Zellen teilen sich Verknüpfungen. Beobachte fünf Trajektorien und vergleiche dann drei Explorationseinstellungen." },
      { name: "Du bist der Boss! Stimme alle Gedächtnisparameter gemeinsam ab!", description: "Trainiere Schlüssel, Tür und den schnellen Weg zur Uhr.", instructions: "Trainiere drei Fähigkeiten mit jeweils mehr als 75 % Wahrscheinlichkeit: den Schlüssel erreichen, die Tür öffnen und von der Tür auf kürzestem Weg zur Uhr gelangen. Schlüssel und erstes Öffnen der Tür bringen je +1; ein Türversuch ohne Schlüssel kostet −1 und die Uhr bringt +10." },
      { name: "Erfinde neue Herausforderungen für Nova", description: "Gestalte die Umgebung und trainiere Nova.", instructions: "Beginne mit einem 4×4-Raum. Verändere Wände, Perzepte, Schlüssel, Tür, Uhr, Falle und Belohnungen. Trainiere Nova, bis sie die Uhr innerhalb von zwei Zusatzschritten mit mindestens 75 % Wahrscheinlichkeit erreicht." },
    ],
  },
};

// English is the canonical lab copy. Every locale inherits that complete shape
// and overrides translated strings, so new interface keys can never disappear
// or drift structurally between languages.
export const LAB_STORY_TEXT = {
  en: LAB_STORY_TEXT_CORE.en,
  de: LAB_STORY_TEXT_CORE.de,
  it: {
    ...LAB_STORY_TEXT_CORE.en,
    brand: "Accademia dei detective", subtitle: "Simulazione proiettiva", modes: "Modalità", returnModes: "Torna alla selezione della modalità",
    kicker: "L’addestramento avanzato di Nova", title: "Laboratorio di ricerca sull’apprendimento",
    summary: "Progetta la stanza di addestramento e le ricompense di Nova. Confronta come glow, oblio e avidità della policy cambiano il suo apprendimento.",
    trainingRoom: "Stanza di addestramento", environmentHint: "Nova esplora la stanza. Ricompensa orologio: +{reward}.",
    memoryTitle: "Memoria di Nova", memoryHint: "Le celle con la stessa percezione condividono le associazioni.",
    progressTitle: "Progresso dell’apprendimento", progressHint: "Segui le ricompense delle indagini di Nova.", roomEditor: "Impostazioni dell’ambiente",
    tuneMemory: "Regola l’apprendimento di Nova", temperatureLabel: "Esplorazione e sfruttamento (temperatura inversa β)",
    temperatureHelp: "Esplora distribuisce ampiamente le azioni, bilancia combina esplorazione e preferenze apprese, mentre sfrutta favorisce fortemente i valori H maggiori.",
    successCriterion: "Successo: probabilità del percorso più breve ≥ 75%",
    successExplanation: "Alla fine di ogni episodio si sommano le probabilità di tutti i percorsi minimi riusciti. Il caso 3 valuta separatamente chiave, porta e percorso minimo dalla porta all’orologio. Il caso 4 consente due passi extra. Il caso 2 termina con un quiz.",
    minimumSteps: "passi minimi", awaitEpisode: "Valutazione alla fine di un episodio.", noRoute: "Nessun percorso valido verso l’orologio. Modifica la stanza.",
    glowExplanation: "La coppia percezione–azione scelta ha glow 1. Tutte le altre coppie decadono del fattore (1 − η) dopo ogni passo.",
    playback: "Modalità di visualizzazione", playbackModes: { click: "Clic", slow: "Lenta", fast: "Veloce", immediate: "Immediata" },
    playbackHints: { click: "Premi Passo per campionare un’azione e muovere Nova.", slow: "Osserva lentamente ogni decisione.", fast: "Osserva lo stesso apprendimento più velocemente.", immediate: "Mostra solo la fine degli episodi." },
    step: "Passo", nextStep: "Prossimo episodio: passo", currentPercept: "Percezione attuale", currentAction: "Azione attuale", noAction: "Non ancora campionata",
    decisionHint: "Nova ha scelto questa azione in base a colore, oggetto e stato della chiave percepiti.", episodeFinished: "Episodio terminato",
    episodeOutcomes: { goal: "Orologio recuperato", trap: "Trappola raggiunta", limit: "Limite di passi raggiunto" },
    hExplanation: "I valori H sono le forze apprese delle connessioni. Ricompensa, oblio e sensibilità alla ricompensa li modificano.",
    policyExplanation: "La policy mostra le probabilità reali delle azioni: softmax dei valori H moltiplicati per β.", coachObservation: "Osservazione del coach",
    observation: "Nova impara dal feedback definito, non dalle intenzioni. Confronta memoria e curve di ricompensa prima di cambiare un’altra impostazione.",
    novaPortrait: "Ritratto di Nova", agentLabel: "Allieva detective Nova", share: "Condividi l’accademia", case: "Caso", trajectories: "traiettorie",
    memoryShown: "Memoria di Nova mostrata come {view}", memoryRepresentation: "Rappresentazione della memoria", glow: "Glow", hValues: "Valori H", policy: "Policy",
    explorePrompt: "Nova ha visto ogni colore. Muovila con esplora, bilancia e sfrutta. Osserva cinque traiettorie reali per impostazione, poi confronta policy e istogrammi delle posizioni.",
    explore: "Esplora", balanced: "Bilancia", exploit: "Sfrutta", compareModes: "Confronta le impostazioni di esplorazione",
    compareRunHint: "Scegli un’impostazione, poi usa Passo o Avvia sopra la stanza. Completa cinque traiettorie per ogni impostazione.",
    mapView: "Vista mappa", fiveTrajectories: "Esegui cinque traiettorie", visited: "Visite dal cambio dell’impostazione", quizQuestion: "Cosa accade quando β aumenta?",
    quizAnswers: ["Nova dimentica più in fretta", "Nova favorisce le azioni con valori H più forti", "I colori diventano unici"], quizTryAgain: "Prova un’altra risposta o confronta di nuovo le policy.",
    reviewModes: "Rivedi le tre modalità", takeQuiz: "Fai il quiz", continue: "Continua", youWon: "Hai vinto!", keyAbsent: "Senza chiave", keyPresent: "Con chiave",
    actions: ["su", "destra", "giù", "sinistra"], novaPosition: "Posizione attuale di Nova",
    cases: [
      { name: "Regola tu la memoria!", description: "Applica ciò che hai imparato in modalità Avventura.", instructions: "Regola glow e oblio e addestra Nova a trovare l’orologio il più rapidamente possibile." },
      { name: "Nova vede il mondo in modo diverso!", description: "Alcune stanze sembrano identiche!", instructions: "Osserva come Nova rappresenta le associazioni tra ciò che vede e il suo comportamento: non è una mappa." },
      { name: "Sei tu a comandare!", description: "Regola insieme tutti i parametri della memoria.", instructions: "Addestra tre abilità oltre il 75%: raggiungere la chiave, aprire la porta e seguire dalla porta il percorso minimo verso l’orologio." },
      { name: "Crea la tua stanza di addestramento.", description: "Progetta l’ambiente e addestra Nova.", instructions: "Distribuisci percezioni, imposta trappole e ricompense, poi chiudi le impostazioni per iniziare l’addestramento." },
    ],
  },
  fr: {
    ...LAB_STORY_TEXT_CORE.en,
    brand: "Académie des détectives", subtitle: "Simulation projective", modes: "Modes", returnModes: "Revenir au choix du mode",
    kicker: "Entraînement avancé de Nova", title: "Laboratoire de recherche sur l’apprentissage",
    summary: "Concevez la salle d’entraînement et les récompenses de Nova. Comparez l’effet du glow, de l’oubli et de la stratégie sur son apprentissage.",
    trainingRoom: "Salle d’entraînement", environmentHint: "Nova explore la salle. Récompense de la montre : +{reward}.", memoryTitle: "Mémoire de Nova",
    memoryHint: "Les cases ayant le même percept partagent leurs associations.", progressTitle: "Progression de l’apprentissage", progressHint: "Suivez les récompenses des enquêtes de Nova.",
    roomEditor: "Paramètres de l’environnement", tuneMemory: "Régler l’apprentissage de Nova", temperatureLabel: "Exploration et exploitation (température inverse β)",
    temperatureHelp: "Explorer répartit largement les actions, équilibrer combine exploration et préférences apprises, et exploiter favorise fortement les plus grandes valeurs H.",
    successCriterion: "Réussite : probabilité du chemin le plus court ≥ 75 %", successExplanation: "À la fin de chaque épisode, les probabilités de tous les chemins minimaux réussis sont additionnées. Le cas 3 évalue séparément la clé, la porte et le chemin minimal de la porte à la montre. Le cas 4 autorise deux pas supplémentaires. Le cas 2 se termine par un quiz.",
    minimumSteps: "pas minimum", awaitEpisode: "Évaluation à la fin d’un épisode.", noRoute: "Aucun chemin valide vers la montre. Modifiez la salle.",
    glowExplanation: "La paire percept–action choisie a un glow de 1. Toutes les autres paires décroissent d’un facteur (1 − η) après chaque pas.",
    playback: "Mode d’affichage", playbackModes: { click: "Clic", slow: "Lent", fast: "Rapide", immediate: "Immédiat" },
    playbackHints: { click: "Cliquez sur Pas pour tirer une action et déplacer Nova.", slow: "Observez lentement chaque décision.", fast: "Observez le même apprentissage plus rapidement.", immediate: "Affichez seulement la fin des épisodes." },
    step: "Pas", nextStep: "Épisode suivant : pas", currentPercept: "Percept actuel", currentAction: "Action actuelle", decisionHint: "Nova a choisi cette action à partir de la couleur, de l’objet et de l’état de la clé perçus.", noAction: "Pas encore tirée",
    episodeFinished: "Épisode terminé", episodeOutcomes: { goal: "Montre récupérée", trap: "Piège atteint", limit: "Limite de pas atteinte" },
    hExplanation: "Les valeurs H sont les forces de connexion apprises. La récompense, l’oubli et la sensibilité à la récompense les modifient.", policyExplanation: "La stratégie montre les probabilités réelles des actions : softmax des valeurs H multipliées par β.",
    coachObservation: "Observation du coach", observation: "Nova apprend à partir du retour défini, pas de vos intentions. Comparez sa mémoire aux courbes de récompense avant de changer un autre réglage.",
    novaPortrait: "Portrait de Nova", agentLabel: "Élève détective Nova", share: "Partager l’académie", case: "Cas", trajectories: "trajectoires", memoryShown: "Mémoire de Nova affichée en {view}",
    memoryRepresentation: "Représentation de la mémoire", glow: "Glow", hValues: "Valeurs H", policy: "Stratégie",
    explorePrompt: "Nova a vu chaque couleur. Déplacez-la en mode explorer, équilibrer et exploiter. Observez cinq trajectoires par réglage, puis comparez la stratégie et les histogrammes de position.",
    explore: "Explorer", balanced: "Équilibrer", exploit: "Exploiter", compareModes: "Comparer les réglages d’exploration", compareRunHint: "Choisissez un réglage, puis utilisez Pas ou Démarrer au-dessus de la salle. Effectuez cinq trajectoires pour chaque réglage.",
    mapView: "Vue de la carte", fiveTrajectories: "Lancer cinq trajectoires", visited: "Visites depuis le changement de réglage", quizQuestion: "Que se passe-t-il lorsque β augmente ?",
    quizAnswers: ["Nova oublie plus vite", "Nova favorise les actions aux valeurs H plus fortes", "Les couleurs deviennent uniques"], quizTryAgain: "Essayez une autre réponse ou comparez encore les stratégies.",
    reviewModes: "Revoir les trois modes", takeQuiz: "Faire le quiz", continue: "Continuer", youWon: "Gagné !", keyAbsent: "Sans clé", keyPresent: "Avec clé", actions: ["haut", "droite", "bas", "gauche"], novaPosition: "Position actuelle de Nova",
    cases: [
      { name: "Réglez vous-même la mémoire !", description: "Appliquez ce que vous avez appris en mode Aventure.", instructions: "Réglez le glow et l’oubli, puis entraînez Nova à trouver la montre le plus vite possible." },
      { name: "Nova voit le monde autrement !", description: "Certaines salles semblent identiques !", instructions: "Observez comment Nova représente les associations entre ce qu’elle voit et son comportement : ce n’est pas une carte." },
      { name: "C’est vous qui décidez !", description: "Réglez tous les paramètres de mémoire ensemble.", instructions: "Entraînez trois aptitudes au-dessus de 75 % : atteindre la clé, ouvrir la porte et suivre depuis la porte le chemin minimal vers la montre." },
      { name: "Créez votre salle d’entraînement.", description: "Concevez l’environnement et entraînez Nova.", instructions: "Distribuez les percepts, placez pièges et récompenses, puis fermez les paramètres pour commencer l’entraînement." },
    ],
  },
  es: {
    ...LAB_STORY_TEXT_CORE.en,
    brand: "Academia de detectives", subtitle: "Simulación proyectiva", modes: "Modos", returnModes: "Volver a la selección de modo", kicker: "Entrenamiento avanzado de Nova", title: "Laboratorio de investigación del aprendizaje",
    summary: "Diseña la sala de entrenamiento y las recompensas de Nova. Compara cómo el glow, el olvido y la estrategia cambian su aprendizaje.", trainingRoom: "Sala de entrenamiento", environmentHint: "Nova explora la sala. Recompensa del reloj: +{reward}.",
    memoryTitle: "Memoria de Nova", memoryHint: "Las celdas con la misma percepción comparten asociaciones.", progressTitle: "Progreso del aprendizaje", progressHint: "Sigue las recompensas de las investigaciones de Nova.", roomEditor: "Ajustes del entorno", tuneMemory: "Ajustar el aprendizaje de Nova",
    temperatureLabel: "Exploración y explotación (temperatura inversa β)", temperatureHelp: "Explorar reparte ampliamente las acciones, equilibrar combina exploración y preferencias aprendidas, y explotar favorece con fuerza los valores H mayores.",
    successCriterion: "Éxito: probabilidad del camino más corto ≥ 75 %", successExplanation: "Al final de cada episodio se suman las probabilidades de todos los caminos mínimos exitosos. El caso 3 evalúa por separado la llave, la puerta y el camino mínimo desde la puerta al reloj. El caso 4 permite dos pasos extra. El caso 2 termina con un cuestionario.",
    minimumSteps: "pasos mínimos", awaitEpisode: "Se evalúa al final de un episodio.", noRoute: "No hay una ruta válida al reloj. Edita la sala.", glowExplanation: "El par percepción–acción elegido tiene glow 1. Los demás pares decaen por un factor (1 − η) después de cada paso.",
    playback: "Modo de visualización", playbackModes: { click: "Clic", slow: "Lento", fast: "Rápido", immediate: "Inmediato" }, playbackHints: { click: "Pulsa Paso para muestrear una acción y mover a Nova.", slow: "Observa lentamente cada decisión.", fast: "Observa el mismo aprendizaje más rápido.", immediate: "Muestra solo el final de los episodios." },
    step: "Paso", nextStep: "Siguiente episodio: paso", currentPercept: "Percepción actual", currentAction: "Acción actual", decisionHint: "Nova eligió esta acción según el color, el objeto y el estado de la llave percibidos.", noAction: "Aún no muestreada", episodeFinished: "Episodio terminado",
    episodeOutcomes: { goal: "Reloj recuperado", trap: "Trampa alcanzada", limit: "Límite de pasos alcanzado" }, hExplanation: "Los valores H son fuerzas de conexión aprendidas. La recompensa, el olvido y la sensibilidad a la recompensa los modifican.", policyExplanation: "La estrategia muestra las probabilidades reales de acción: softmax de los valores H multiplicados por β.",
    coachObservation: "Observación del entrenador", observation: "Nova aprende de la respuesta definida, no de tus intenciones. Compara su memoria con las curvas de recompensa antes de cambiar otro ajuste.", novaPortrait: "Retrato de Nova", agentLabel: "Alumna detective Nova", share: "Comparte la academia", case: "Caso", trajectories: "trayectorias", memoryShown: "Memoria de Nova mostrada como {view}", memoryRepresentation: "Representación de la memoria", glow: "Glow", hValues: "Valores H", policy: "Estrategia",
    explorePrompt: "Nova ha visto cada color. Muévela con explorar, equilibrar y explotar. Observa cinco trayectorias por ajuste y compara la estrategia y los histogramas de ubicación.", explore: "Explorar", balanced: "Equilibrar", exploit: "Explotar", compareModes: "Comparar ajustes de exploración", compareRunHint: "Elige un ajuste y usa Paso o Iniciar sobre la sala. Completa cinco trayectorias por ajuste.", mapView: "Vista del mapa", fiveTrajectories: "Ejecutar cinco trayectorias", visited: "Visitas desde el cambio de ajuste", quizQuestion: "¿Qué ocurre cuando aumenta β?", quizAnswers: ["Nova olvida más rápido", "Nova favorece acciones con valores H más fuertes", "Los colores se vuelven únicos"], quizTryAgain: "Prueba otra respuesta o compara de nuevo las estrategias.", reviewModes: "Revisar los tres modos", takeQuiz: "Hacer el cuestionario", continue: "Continuar", youWon: "¡Ganaste!", keyAbsent: "Sin llave", keyPresent: "Con llave", actions: ["arriba", "derecha", "abajo", "izquierda"], novaPosition: "Posición actual de Nova",
    cases: [
      { name: "¡Ajusta tú la memoria!", description: "Aplica lo aprendido en el modo Aventura.", instructions: "Ajusta el glow y el olvido y entrena a Nova para encontrar el reloj lo antes posible." },
      { name: "¡Nova ve el mundo de otra manera!", description: "¡Algunas salas parecen idénticas!", instructions: "Observa cómo Nova representa las asociaciones entre lo que ve y su conducta: no es un mapa." },
      { name: "¡Tú mandas!", description: "Ajusta todos los parámetros de memoria a la vez.", instructions: "Entrena tres habilidades por encima del 75 %: llegar a la llave, abrir la puerta y seguir desde la puerta el camino mínimo hasta el reloj." },
      { name: "Crea tu sala de entrenamiento.", description: "Diseña el entorno y entrena a Nova.", instructions: "Distribuye percepciones, trampas y recompensas, y cierra los ajustes para iniciar el entrenamiento." },
    ],
  },
};
